name: PyPI Deployment

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name : Print GitHub context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }} 
      run: echo "$GITHUB_CONTEXT" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo Running in $PWD
        python -m build
        twine upload dist/*
